/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRisksRouteImport } from './routes/_authenticated/risks'
import { Route as AuthenticatedKpisRouteImport } from './routes/_authenticated/kpis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCapaRouteImport } from './routes/_authenticated/capa'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedAuditsRouteImport } from './routes/_authenticated/audits'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents.index'
import { Route as AuthenticatedChecklistsIndexRouteImport } from './routes/_authenticated/checklists.index'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedChecklistsIdRouteImport } from './routes/_authenticated/checklists.$id'
import { Route as AuthenticatedChecklistsIdFillRouteImport } from './routes/_authenticated/checklists.$id_.fill'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRisksRoute = AuthenticatedRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKpisRoute = AuthenticatedKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCapaRoute = AuthenticatedCapaRouteImport.update({
  id: '/capa',
  path: '/capa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditsRoute = AuthenticatedAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChecklistsIndexRoute =
  AuthenticatedChecklistsIndexRouteImport.update({
    id: '/checklists/',
    path: '/checklists/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChecklistsIdRoute =
  AuthenticatedChecklistsIdRouteImport.update({
    id: '/checklists/$id',
    path: '/checklists/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChecklistsIdFillRoute =
  AuthenticatedChecklistsIdFillRouteImport.update({
    id: '/checklists/$id_/fill',
    path: '/checklists/$id/fill',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/capa': typeof AuthenticatedCapaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kpis': typeof AuthenticatedKpisRoute
  '/risks': typeof AuthenticatedRisksRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/checklists/': typeof AuthenticatedChecklistsIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/checklists/$id/fill': typeof AuthenticatedChecklistsIdFillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/capa': typeof AuthenticatedCapaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kpis': typeof AuthenticatedKpisRoute
  '/risks': typeof AuthenticatedRisksRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/checklists': typeof AuthenticatedChecklistsIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/checklists/$id/fill': typeof AuthenticatedChecklistsIdFillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/audits': typeof AuthenticatedAuditsRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/capa': typeof AuthenticatedCapaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kpis': typeof AuthenticatedKpisRoute
  '/_authenticated/risks': typeof AuthenticatedRisksRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/checklists/$id': typeof AuthenticatedChecklistsIdRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/checklists/': typeof AuthenticatedChecklistsIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/checklists/$id_/fill': typeof AuthenticatedChecklistsIdFillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/audit-logs'
    | '/audits'
    | '/backup'
    | '/capa'
    | '/dashboard'
    | '/kpis'
    | '/risks'
    | '/settings'
    | '/submissions'
    | '/users'
    | '/checklists/$id'
    | '/documents/$id'
    | '/checklists/'
    | '/documents/'
    | '/checklists/$id/fill'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/audit-logs'
    | '/audits'
    | '/backup'
    | '/capa'
    | '/dashboard'
    | '/kpis'
    | '/risks'
    | '/settings'
    | '/submissions'
    | '/users'
    | '/checklists/$id'
    | '/documents/$id'
    | '/checklists'
    | '/documents'
    | '/checklists/$id/fill'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/audit-logs'
    | '/_authenticated/audits'
    | '/_authenticated/backup'
    | '/_authenticated/capa'
    | '/_authenticated/dashboard'
    | '/_authenticated/kpis'
    | '/_authenticated/risks'
    | '/_authenticated/settings'
    | '/_authenticated/submissions'
    | '/_authenticated/users'
    | '/_authenticated/checklists/$id'
    | '/_authenticated/documents/$id'
    | '/_authenticated/checklists/'
    | '/_authenticated/documents/'
    | '/_authenticated/checklists/$id_/fill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/risks': {
      id: '/_authenticated/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof AuthenticatedRisksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kpis': {
      id: '/_authenticated/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof AuthenticatedKpisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capa': {
      id: '/_authenticated/capa'
      path: '/capa'
      fullPath: '/capa'
      preLoaderRoute: typeof AuthenticatedCapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audits': {
      id: '/_authenticated/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuthenticatedAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checklists/': {
      id: '/_authenticated/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthenticatedChecklistsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checklists/$id': {
      id: '/_authenticated/checklists/$id'
      path: '/checklists/$id'
      fullPath: '/checklists/$id'
      preLoaderRoute: typeof AuthenticatedChecklistsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checklists/$id_/fill': {
      id: '/_authenticated/checklists/$id_/fill'
      path: '/checklists/$id/fill'
      fullPath: '/checklists/$id/fill'
      preLoaderRoute: typeof AuthenticatedChecklistsIdFillRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedAuditsRoute: typeof AuthenticatedAuditsRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedCapaRoute: typeof AuthenticatedCapaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKpisRoute: typeof AuthenticatedKpisRoute
  AuthenticatedRisksRoute: typeof AuthenticatedRisksRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedChecklistsIdRoute: typeof AuthenticatedChecklistsIdRoute
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
  AuthenticatedChecklistsIndexRoute: typeof AuthenticatedChecklistsIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedChecklistsIdFillRoute: typeof AuthenticatedChecklistsIdFillRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedAuditsRoute: AuthenticatedAuditsRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedCapaRoute: AuthenticatedCapaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKpisRoute: AuthenticatedKpisRoute,
  AuthenticatedRisksRoute: AuthenticatedRisksRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedChecklistsIdRoute: AuthenticatedChecklistsIdRoute,
  AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  AuthenticatedChecklistsIndexRoute: AuthenticatedChecklistsIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedChecklistsIdFillRoute: AuthenticatedChecklistsIdFillRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
